spring:
  application:
    name: wallet-transfer-system

  # VIRTUAL THREADS CONFIGURATION
  threads:
    virtual:
      enabled: true

  # CUSTOM CONFIGURATION
  configuration:
    redis:
      idempotency:
        # 5000ms -> 5s
        lock-ttl: 5000
        # 86400000ms -> 24h
        cache-ttl: 86400000

  # FLYWAY MIGRATION CONFIGURATION
  flyway:
    locations: classpath:db/migration
    enabled: false

  # DATABASE CONFIGURATION
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet-transfer
    username: postgres
    password: admin123@
  
  jpa:
#    hibernate:
#      ddl-auto: validate
#    show-sql: true
    # properties:
    #   hibernate:
    #     format_sql: true

  # REDIS CONFIGURATION
  data:
    redis:
      host: localhost
      port: 6379
