spring.application.name=wallet-transfer-system

# FLYWAY MIGRATION CONFIGURATION
spring.flyway.locations=classpath:db/migration
#spring.flyway.enabled=false

# DATABASE CONFIGURATION
spring.datasource.url=jdbc:postgresql://localhost:5432/wallet-transfer
spring.datasource.username=postgres
spring.datasource.password=admin123@
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


