-- CREATE TABLE WALLETS
CREATE TABLE PUBLIC.WALLETS (
	ID UUID NOT NULL PRIMARY KEY,
	WALLET_NUMBER VARCHAR(255) UNIQUE NOT NULL,
	OWNER_ID UUID NOT NULL,
	BALANCE NUMERIC(20, 2) NOT NULL DEFAULT 0,
	CURRENCY VARCHAR(3) NOT NULL,
	STATUS VARCHAR(255) NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	VERSION BIGINT NOT NULL DEFAULT 0
);

-- CREATE TABLE CUSTOMERS
CREATE TABLE PUBLIC.CUSTOMERS (
	ID UUID NOT NULL PRIMARY KEY,
	FULL_NAME VARCHAR(255)
);

-- CREATE TABLE TRANSACTIONS
CREATE TABLE PUBLIC.TRANSACTIONS (
	ID UUID NOT NULL PRIMARY KEY,
	IDEMPOTENCY_KEY VARCHAR(255) UNIQUE NOT NULL,
	SOURCE_WALLET_ID UUID,
	TARGET_WALLET_ID UUID,
	AMOUNT NUMERIC(20, 2) NOT NULL DEFAULT 0,
	CURRENCY VARCHAR(3) NOT NULL,
	STATUS VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255),
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CREATE TABLE LEDGER_ENTRIES
CREATE TABLE PUBLIC.LEDGER_ENTRIES (
	ID UUID NOT NULL PRIMARY KEY,
	TRANSACTION_ID UUID NOT NULL,
	WALLET_ID UUID,
	AMOUNT NUMERIC(20, 2) NOT NULL DEFAULT 0,
	CURRENCY VARCHAR(3) NOT NULL,
	TYPE VARCHAR(255) NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);